In [1]:
import numpy as np


In [2]:
import os
os.getcwd()

'C:\\Users\\Garima\\Documents\\numpy'

In [3]:
data = np.loadtxt('cnt_km_year_powerPS_minPrice_maxPrice_avgPrice_sdPrice1.txt')

In [4]:
data

array([[1.90000000e+01, 1.25000000e+05, 1.99100000e+03, ...,
        1.49900000e+03, 6.48315800e+02, 3.52035293e+02],
       [6.90000000e+01, 1.50000000e+05, 1.99100000e+03, ...,
        1.60000000e+03, 5.16434800e+02, 3.46767661e+02],
       [1.10000000e+01, 9.00000000e+04, 1.99100000e+03, ...,
        1.00000000e+04, 2.34245450e+03, 3.01743233e+03],
       ...,
       [2.50000000e+01, 2.00000000e+04, 2.01500000e+03, ...,
        8.27000000e+04, 3.96833200e+04, 1.30650723e+04],
       [2.20000000e+01, 1.00000000e+04, 2.01500000e+03, ...,
        6.84500000e+04, 5.03726364e+04, 1.07362651e+04],
       [1.60000000e+01, 2.00000000e+04, 2.01500000e+03, ...,
        8.58000000e+04, 5.80962500e+04, 1.40029336e+04]])

In [5]:
data.T

array([[1.90000000e+01, 6.90000000e+01, 1.10000000e+01, ...,
        2.50000000e+01, 2.20000000e+01, 1.60000000e+01],
       [1.25000000e+05, 1.50000000e+05, 9.00000000e+04, ...,
        2.00000000e+04, 1.00000000e+04, 2.00000000e+04],
       [1.99100000e+03, 1.99100000e+03, 1.99100000e+03, ...,
        2.01500000e+03, 2.01500000e+03, 2.01500000e+03],
       ...,
       [1.49900000e+03, 1.60000000e+03, 1.00000000e+04, ...,
        8.27000000e+04, 6.84500000e+04, 8.58000000e+04],
       [6.48315800e+02, 5.16434800e+02, 2.34245450e+03, ...,
        3.96833200e+04, 5.03726364e+04, 5.80962500e+04],
       [3.52035293e+02, 3.46767661e+02, 3.01743233e+03, ...,
        1.30650723e+04, 1.07362651e+04, 1.40029336e+04]])

In [6]:
count,km,year,powerPS,minPrice,maxPrice,avgPrice,sdPrice = data.T

In [7]:
sdPrice

array([  352.0352932,   346.7676614,  3017.432333 , ..., 13065.07229  ,
       10736.26507  , 14002.93357  ])

In [8]:
avgPrice

array([  648.3158,   516.4348,  2342.4545, ..., 39683.32  , 50372.6364,
       58096.25  ])

In [9]:
maxPrice

array([ 1499.,  1600., 10000., ..., 82700., 68450., 85800.])

In [10]:
minPrice

array([  300.,   110.,   330., ...,   487., 33000., 33950.])

In [11]:
powerPS

array([ 40.,  40.,  60., ..., 300., 320., 320.])

In [12]:
year

array([1991., 1991., 1991., ..., 2015., 2015., 2015.])

In [13]:
km

array([125000., 150000.,  90000., ...,  20000.,  10000.,  20000.])

In [14]:
count

array([19., 69., 11., ..., 25., 22., 16.])

In [15]:
#INDEXING

In [16]:
cnt_km_year_powerPS_minPrice_maxPrice_avgPrice_sdPrice1 = data[:,1:]

In [17]:
cnt_km_year_powerPS_minPrice_maxPrice_avgPrice_sdPrice1

array([[1.25000000e+05, 1.99100000e+03, 4.00000000e+01, ...,
        1.49900000e+03, 6.48315800e+02, 3.52035293e+02],
       [1.50000000e+05, 1.99100000e+03, 4.00000000e+01, ...,
        1.60000000e+03, 5.16434800e+02, 3.46767661e+02],
       [9.00000000e+04, 1.99100000e+03, 6.00000000e+01, ...,
        1.00000000e+04, 2.34245450e+03, 3.01743233e+03],
       ...,
       [2.00000000e+04, 2.01500000e+03, 3.00000000e+02, ...,
        8.27000000e+04, 3.96833200e+04, 1.30650723e+04],
       [1.00000000e+04, 2.01500000e+03, 3.20000000e+02, ...,
        6.84500000e+04, 5.03726364e+04, 1.07362651e+04],
       [2.00000000e+04, 2.01500000e+03, 3.20000000e+02, ...,
        8.58000000e+04, 5.80962500e+04, 1.40029336e+04]])

In [18]:
np.argmax(cnt_km_year_powerPS_minPrice_maxPrice_avgPrice_sdPrice1, axis = 0)

array([   1, 1726,  882, 1561,  448, 1443,   22], dtype=int32)

In [19]:
cnt_km_year_powerPS_minPrice_maxPrice_avgPrice_sdPrice1.max()

150000.0

In [20]:
cnt_km_year_powerPS_minPrice_maxPrice_avgPrice_sdPrice1.sum()

230647066.4807452

In [21]:
#BROADCASTING

In [22]:
a = np.tile(np.arange(1,40,10),(3,1))

In [23]:
print(a)

[[ 1 11 21 31]
 [ 1 11 21 31]
 [ 1 11 21 31]]


In [24]:
a = a.T
a

array([[ 1,  1,  1],
       [11, 11, 11],
       [21, 21, 21],
       [31, 31, 31]])

In [25]:
b = np.array([0,1,2])

In [26]:
b

array([0, 1, 2])

In [27]:
print(a+b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [28]:
a

array([[ 1,  1,  1],
       [11, 11, 11],
       [21, 21, 21],
       [31, 31, 31]])

In [29]:
n = np.arange(0,40,3)

In [30]:
n

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [31]:
n.shape

(14,)

In [32]:
n.ndim

1

In [33]:
n = n.T

In [34]:
n

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [35]:
b

array([0, 1, 2])

In [37]:
n = n[:, np.newaxis ]

In [38]:
n

array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18],
       [21],
       [24],
       [27],
       [30],
       [33],
       [36],
       [39]])

In [39]:
n.shape

(14, 1)

In [40]:
n+b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41]])

In [41]:
#in-place sort

In [43]:
a.sort(axis = 1)
a

array([[ 1,  1,  1],
       [11, 11, 11],
       [21, 21, 21],
       [31, 31, 31]])

In [46]:
a = np.array([9,0,7,8])
j = np.argsort(a)

In [47]:
j

array([1, 2, 3, 0], dtype=int32)

In [48]:
a[j]

array([0, 7, 8, 9])

In [49]:
array([1,2,3])

NameError: name 'array' is not defined

In [50]:
import random
t=int(input())
for i in range(t):
    n=int(input())
    if n%4!=1:            
        print('BOB')
    else:
        print('ALICE')

2
1
ALICE
2
BOB
